name: Release on npm

on:
  release:
    types: [published]

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write # Required for obtaining OIDC token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # npm trusted publishing requires npm 11.5.1 or later
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
